---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mqtt-exporter
    app.kubernetes.io/instance: mqtt-exporter
spec:
  selector:
    app.kubernetes.io/name: mqtt-exporter
    app.kubernetes.io/instance: mqtt-exporter
    prometheus.io/port: 9641
    prometheus.io/scrape: true
  ports:
  - name: monitoring
    port: 9641
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: monitoring
  name: mqtt-exporter
  labels:
    app.kubernetes.io/name: mqtt-exporter
    app.kubernetes.io/instance: mqtt-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt-exporter
      app.kubernetes.io/instance: mqtt-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mqtt-exporter
        app.kubernetes.io/instance: mqtt-exporter
    spec:
      containers:
      - name: mqtt-exporter
        image: hikhvar/mqtt2prometheus:v0.1.5
        imagePullPolicy: IfNotPresent
        ports:
        - name: monitoring
          containerPort: 9641
        volumeMounts:
        - name: m2p-cv
          mountPath: /config.yaml
          subPath: config-yaml
          readOnly: true
      volumes:
      - name: m2p-cv
        configMap:
          name: mqtt2prometheus-config