---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mqtt-exporter
  namespace: default
  labels:
    app.kubernetes.io/name: mqtt-exporter
spec:
  endpoints:
  - path: /metrics
    targetPort: monitoring
  jobLabel: mqtt-exporter
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt-exporter
