---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
