# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: longhorn-aws-secret
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QrRc+gLjU9MT2FdnSjPolrdFcEY=,iv:evsWjTG+6Kh2f3tvXY/dIkHWJiHRbNtj0l6JEf2NhCI=,tag:fG8wa60xnOy061Ju93/TtQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Dufl/Ra6iwg83e3emj6iP5nttC0Bx4Wv1yidJFz7RG+pDZP5zMLXzg==,iv:S8GnbfBxEf4HZ0DdR7VEWl/Wz9CINOSnBMPbJwqA4f8=,tag:vz7YJv6gSUofswzV1HvWoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-01T12:15:54Z"
    mac: ENC[AES256_GCM,data:J9Fe1noY/vPhcucv2Omda6GiDqZj1h0qdPbI+/fZSDFUv04zmkaQLUtatnkIWaQ7MPM0GE09Z21mMVfq7xMgRp5EJD/Pr5aRFHi3o4lKe4eBl+VI0ogp85VrP3XB5kOdV6jhlox157G2Z0Z0S8U50odatNEIsWmpEUpBHgCvehQ=,iv:9WczuMJTETT5bP/mwBvbgW51YFnsXInkllvA2e0BtwI=,tag:6t4tjKECiEX0cb74P/NbIQ==,type:str]
    pgp:
        - created_at: "2021-07-01T12:15:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4KcvqgHb192AQ/+LIyLJAmtwhs1x1qASYobmTYQrzbOBK9XQZkHE8TUIHsI
            Rby9LmMzluC+4JW4wt/z2d0fWgPyVm1xRBKIG9cDTBB1GOEcZRAG6DvG1uW/CQOf
            WLozsviYDbA0f+Uvj4MFi5343YXgz3xJ41GGab0VJqpWlraxMtU+nBE3JUAYXFAe
            VIhQF/YpZbIkRMLGbw/5nZvsx5Emf01IcSlgdmm8OOgJnMeCil9c5WDo3nSzd92K
            Z8HzkWbWGuYnLEo97qtTAS56UsoBNIPkS9b80/x9l53qEy0Hq1yHQ0KgySFBHbqv
            cRKJoLovNbD+SLrzgZhEGtLNusQejEIahjOsvJViKd9q35/SsuNDDKCuR4yEGb8D
            sY0em7a3vdiq8FYXd5CD584qkNuI+8z8PvyTXIKFbX7aJOW5Rz5kVJpjTAMMrpe7
            p6wAL7CvPSF6KNG1BfUFVpas8R8KEZLaJ+MhNl0s6UPrGJlPJNBjUwksX8xQQAbK
            QGgWrS68ULkS7HUTcabvQ5QYfchzKanWFcyu7dFXv+m9T3qAYfN9zFd2l4WL3mRs
            YyML5uKEOOKUTSlpCNviq7sDE4eL7GzhGIzCQkC6aXJbZ6+KAUK1aa/4dW/py8bA
            6Us8HlKAyYxpurVCh4/TgW/MGwRLO3MdlDWJOvrc4/X9ggwzOrmTisXmEcBpuarS
            XgH0NbuTmV3Ny0V4qRpwL6VOI2RuoKq3ML25FSMzAqAOuaoy5OL37bEr/gmfj5LZ
            +d1cHm6XUhqZ2QwTkMINJDWZyMvdeFmYW+3zqKSK5m4Cgga9V/j04YxIMqOYl8c=
            =JcZ/
            -----END PGP MESSAGE-----
          fp: 3627F1BFED9A91B9D1098A902975378CB9A1B903
        - created_at: "2021-07-01T12:15:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxzJHnRk0chmAQ//YybXjAHGOoKmxPIR5+QT3hI4yo9ZOt0MuIwD+5IlDf78
            SLUYW2i1YRyuNryEiBFa6TDqKgi+siagi334yEZrqDkUxjVx27qhB+0GGkM0qo95
            8mADPL4D75VfFJhCRA6Cg31Y2oWZ+1hfuRnjgCL+0jnuNiOiUmgUjk4zNv6vRFM+
            Hk+3XN9DxvRm7LggWv9udKjKszCPtCvkZqibCjE842WgK2PVR1hX++iamQ6l28M1
            MZma5bywO4/sbhhD+SgnQCPohulBgAo1aOa58Md4UA/IKjZnxQDKpxfMSY8ENIQH
            SeGwbVNMTL/J+/xZw+8na2qU+LbNiLsjMHQGxe8lRDnlwp3Deh/F1G/RuVmgS76T
            9bWdG/xAJhU9GdzhZtWPzsxfHVPKJwtE4Xgfq7JxoPhat+l7NOHE8RHHoHg2rGB+
            xrD8UxTUwy2FAvApiTeDx3bG5ayBr4ut6kjGGLb7t+SObABSn5T/ac3xsLm1YM9v
            OgWMPPdio90izk3rX8eBmuCcfvUF9aKeVOcyrNG3A+p3C/v1+TXHNQgaI7Mwyx1J
            aY09ppCcXjkcN8UmWGI7+WczbekTYiuZ+1X1CYKgD26L+/Kampe+RNjjKqp8MLde
            /JWzDy7xn7ZoFTSTpXL4/cC584Dl0HNgWj3xZKQzHyTaC4Uohikmq8RJ5ZuyyIDS
            XgGuw+3xoKwqL1rLHSMWNrObX9my6BzZkgfVMxjHryBtqWbpTu0q1Ze1vbaDK5c3
            Gj7umlDggQLyHE+8Nnq9w/fqGnJoAHH8lB8spYyvYXeM/r7aupmqSX5gChsRKSI=
            =MMVf
            -----END PGP MESSAGE-----
          fp: 0F074212D05FD1A4875B719F174362ACE786CCDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
