---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homer
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: b4bz/homer
      tag: 21.03.2
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      ingressClassName: "traefik"
      hosts:
      - host: "homer.${INTERNAL_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      - host: "www.timvw.co.uk"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "homer.${INTERNAL_DOMAIN}"
        - "www.timvw.co.uk"
    persistence:
      config:
        enabled: true
        existingClaim: homer-config
        mountPath: /www/assets
