---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kanboard
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: kanboard
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: kanboard/kanboard
      tag: v1.2.20
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        hosts:
        - host: "kanboard.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "kanboard.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: kanboard-data
        mountPath: /var/www/app/data
