---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanboard-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
