---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mqtt2prometheus
  namespace: default
spec:
  interval: 5m
  values:
    image: ghcr.io/hikhvar/mqtt2prometheus:latest"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9641
    volumes:
      - name: m2p-cv
        configMap:
          name: mqtt2prometheus-config
    volumeMounts:
      - name: m2p-cv
        mountPath: /config.yaml
        subPath: config-yaml
        readOnly: true
