# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:xyumcnsU3sg02Kk7GFkprvip12w=,iv:spIvxrC5hgLP2jhhu4GM+2fpOeatbt6VR4bzja8Avqk=,tag:dhgjNR9wvURHSFQ7BX6PAg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:80h7DDDN8Ta1sHQ94yhw,iv:ZLvB24DPrh5Eb3YU1EEHbXp3/stPqdSULBOLinVJwXc=,tag:/FaAScPNvWuVVG7Zlm4vNw==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:hvCEpH3dvFi1k42W//NB9R5Zcv9pbIB+mq132m8Mc1R70xbRcZmZtYBEw+h3ptZXQn39P9S5dkJbWon+bHmguc7g9Awi1oazLQD1bY1qSJSKG8wJpJytvacs/nL+Dfn1wo2eOgNyDOT2FYCm8ik1bi167eZLbHmh,iv:AaFeTjiJKcMRy8ErjnK/H+6aDTUWqU/SUohUWi/WOMA=,tag:hthyi42RSeXG8oASPfUw4w==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:BS70HcF2yA4=,iv:Gd5ql+mPGykOie0o6Fp5TjDFyH+u7yYVe6DCSJBV4DU=,tag:ValswEW0WV2SpEZnO4S5SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-24T11:41:40Z"
    mac: ENC[AES256_GCM,data:4xGGTpU5Te080P2qqJA+akAT7d/OrxCOeu5DzsPkZ0yPnfzXae5ag+oYBza/Vils2vNBvsCl8sPaKT/QKoCV+bDmELXP0Wp32aCjG0ySHJl3AXvmJ7Lau63/+4B63MTenPLZpmmYjqYAfk4qsbUJMRKhsCoEcsJ5YbbMnF/NHP8=,iv:1yUWqKnBcw3851Gc+maVGFyw0Xrfwg8JJTVFcG0aRTo=,tag:jzLNI0slNFfTSDFZYqDP0A==,type:str]
    pgp:
        - created_at: "2021-06-24T11:41:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4KcvqgHb192ARAAroGf7AkCZb74cO0+HaJELLVhVyhU+vSPnzaBdMJUWq4H
            7u2Q/2je+Lj9ltZVNUtHrJ0lRv1epnoW1XAUFJDC1AYonjQqCSUeZVlMQKyAMMDM
            RgnUwxGHDLisNdVqm6PMSJwytIuKDzpRmBKC5YXKtp+OyPjwcAIJMkKnkgXfxJiy
            Mbdzy2k2jBATjiEpLm3X7+MHa8DeeM/0BBVf/URlSzBmmggj4CC3qJZyVPQMYyYm
            DEXd/hR0sE6xhmM3C7Kir9x16Frhx5OsClpVACujiXRpSiDQ1mm2z3qaQdi2f1AR
            qmKaaEGbXwhbgWpNQL08upNJR4hO/F+7i1nMrgBmtWxmRy4uG7s9xDyy1l+Qp9JD
            OImDOkx7Y0921B/kusuqEjFQHrNaZlDasNFMwJb3aXvvdyL4uh8OljEkmUTnfcNU
            YtiGWhoRjJQcOrmZ2OIPaOl1sdxvVemENuYudXc91gkiTq2WSo/plX8R+PmuOLVk
            GZYgCOKuE8TK9pUgSiRpr33fHChf+gLu4Zfkk+xJoWfRd5GNw5Y1BuWRUg6dzsCo
            gC77FKbfDIEi9LgHDJqZIexYPE+xT/TCW2rH/Tnou9M2pr0JFn+dF9PZjrTGXzyi
            KCoDNXbmtQLfZ8EuCt5HJhSPyGMMda1Zp/VUm6ft43wHBVyQNXhedcbz30dbcc/S
            XAEXBkrDx73Xse2LsIwpZUUEhTJ6aVCHgg2R8aZDXAQ6M1Qz4Gq5fTiIWR25f42n
            q5iSdrypbiolbI0WhGs0YxLvmcQKeD8rRldBRi5UiMIMXCD5p8Qq/kMQOim+
            =hyZ3
            -----END PGP MESSAGE-----
          fp: 3627F1BFED9A91B9D1098A902975378CB9A1B903
        - created_at: "2021-06-24T11:41:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxzJHnRk0chmAQ//TAaO5PVPQnuBan/LyyXs7fbs25pMiiW/CCFOZi68gIAK
            d7Dz17S0yOtLyyPx3iVDNPWb2vcsPSYBXM/JbfezkQpgy398zlsHhxevc3fyWz+2
            X6JoOeR0ACGf3OlPWQQ4lyOVsk59zyXeCz3xoRfEglqmO4VKvrN1chw+i7KITuZg
            7O8H+vmGDkJog22nMjj1hiPVwyLjIT9sEpL0O9bKhuoxS75PowtOGA6ukkeBfttf
            PCwhMvtrC7cJWtHGRbU7qGtUBfpUUc2p6jblBIAEmQGyidoHaWtEyXia0Qrd/aNr
            rC6WuoKSIUedqsr+DwUGxMq1G/csHGeFE/DOsrobwzmSDTe7R9jwf6oAWQSEKS65
            4Pw6+c8/nuPZlfzG0rr7ib9N3zQjYIZapwVJF9gGxt2CPa0vtoUBm9aADehih1T9
            MPv6rz60Yg+AQgcpj7DhVIl2J2PS3rWad138AdhpYs8znZYrRhuGd22M7rDD+9jX
            ajWjDGdO/34+RAuoMbpYxXY29oTzvzSQoBBYQ2Llkbkd+9Nhz1JTP1l3S55huY96
            jrFyZQpfKLWU6FX818ugcLo1xB2Cttu7GcPcVhBV+sd1lzY5f+JPu3EImzROBSyy
            GG9Xjp5VRF4XmHgSbxTkg6NrDQgAwuWrV6bML9vfG2gKUzhpwH6ZdDuUSqsAiv/S
            XAFebeHhSbXLZvjObQUdpE3UNFD50/YKoFgv2mtGZhsvRas2ogidh8aa1Ju3iWGV
            CQydFykFJPlZcAp+P7yud8/0USLfccFMlaGelxl2nlmqDl3WaKSltXdCr0PL
            =SkRB
            -----END PGP MESSAGE-----
          fp: 0F074212D05FD1A4875B719F174362ACE786CCDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
