# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:XqVC6y4Fve4OhHuoOwKFknqtYNU=,iv:69k5BwKuS22UOMO+GYxWdNCoFbN3ONi79KUXfR82qG8=,tag:JvCs7yWhOTGlhAgF01kDzw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:wJQP/vK4g+V3SQGWCDO1,iv:Hz2pxhwzR4XbJ/nrxzoTL5neFE3HANjc+UrlQm0YaKA=,tag:+UN4QcUDDgKWwe5DPgV8Kg==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:mNhp7in8ww==,iv:TBe0E7uYDxAyoodj8MPwROHyieVNYZf7PtRymEwjwEA=,tag:xeNNtdlcmY7DQXDhgEPdHw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:FHvmvL5KnxM=,iv:9Rw6FBxK3m/zRmoG92pQrFL4oaNAkPBNtGaF9i54QwQ=,tag:NJrHVsIctVrJuqi+6X3tIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-22T12:37:53Z"
    mac: ENC[AES256_GCM,data:yCmWNPKimYsdjrjNm17oZfwiaQ4plHLsJN9YA1AbAaMQcuhmXtgsHFKZNKpsDM3ajNtNZPI5P3oi/P30Xufj+1/fkDWI0h1ScLRjmTHdKicDOARE4b/Tfn9oUSMpyggCNKJdCtx1fxxDUA0QFkZNEudD0eofr130NgmdenTm5tQ=,iv:kzCrXobWtPKCz5UOYnV6PbE0cB3uen8l3CriezYl3Fo=,tag:1BwC4wCh6a1PBZONTKJKWg==,type:str]
    pgp:
        - created_at: "2021-06-22T12:37:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4KcvqgHb192AQ//Xl3QAImJFEnKyg2ylHw+EYj6dAIpIFVL59HdnA06Ttcj
            Wtm+53cZAWe2KxkdRGCqkhMDqkWCPessHQnBEn8eQUBqWcru/Qhg9vw25MNo6l5L
            R193BYm8KJ2lCfYYyzafUytTDaKvB176JZVbtoE3v2fYorjiUPFfM0soxwSq3Z3O
            JveY2QTH6qcShFnaZWy/Eq+xS/zyOyrT39t+3OJPgqmsXVDS4h0xSsfVXGgm4+7z
            CHmUkGO3jk/etgXViSf/YlnsmzchnRkGXNOiDQGnpAHS22IhD0COMMBqsKj9yev2
            fLxwixyT2UCVbzX1zBjW3RUa8Ag7zcvupBGW/OV7bgrHF6VHcZho0SiNnUUTcpaK
            UB8cNhEJ40VAuuvCFzqwQmBtw1/L7nSNXUKyAjRGEzdHna/vguhBFjQ8QA767Vfi
            OVrZrAxBnQosHlqHH/AfBz4gr96W0pw9bnc2hjFloxIh+fdZa5AS4j3h4v+cwo5T
            FN2OlkgofRiIr0dcGgXhspCnLzj6ph3w0ezhYVIrk2uFjhYETp3tAQ/y+5FMmxtR
            zuhbhPHAJszxwQRIwZB53QWuucm5D6U6tglZHuVqoNTJbO5wq7ApdAeYrMc6sngU
            k+zSmbywFPw8zhAsGV4UBIsvjpCSX6DowNyf1768e2XwVK+matKD5ppuvw20DFDS
            XgFTfncyj4izSNtSWO4Abrl5Wt6Tkj5A5sjUZADF3k7oaLqaKlkY37bw0g40k7fO
            J9cQlQmwWTQjOQgUa2W+N28GKXXq0EVUPkMwRIgWj26jr92N4b1A7h06nzDLqKA=
            =BM4U
            -----END PGP MESSAGE-----
          fp: 3627F1BFED9A91B9D1098A902975378CB9A1B903
        - created_at: "2021-06-22T12:37:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxzJHnRk0chmARAAoA688EW4q1tCRZqGtNld8RHHxpNKgH+8nXL8UlEPpf2m
            RNs+MrnykCaBGJPQcK/vVJfLtF9ftV2FDQJWmpI1PHqvQK57afCH/wonD+x9C55O
            czalDD1+cscpI/jBUNFQGd4UONIQNnJvicFZkM34ANCDK2p2RiOigm0H6Gm7eE9l
            a1ffZronWx8MifOjmNjYdbYjNN76jU8tWcWr9Gq0bAtrXvCaBAxs8DM2WyOCZUnQ
            0h8yQjetiN+lkzDU2J+BXvEcEuZXd7JKcvkMPIGzL1VrtttY7EtO0mgEweUmGvuS
            Xnm0OGqhH+f34DDLr5aIEENY8isI27QjIc5FtuuO1uTAlcnR2JUmXtoqMy+2HngZ
            HgYiHa9l7ngP7MIXPzO0/rclGPdeV94Z061rYOzOQlGrIEKwid4TajqepSK26pyz
            nl95IDJEKA4lm8tA2XkM+snKYZnrPiKBP3iTtv5YQ4HSzGsrdF1XQwTMKISiwMDu
            AzbDEOsPWGlx3TQNXevs+i76RSrkHMZpJSAJtxnQA+jU89VbnZNSQI63QfNFTeSu
            q0jmlYmav2rl3rpm70aNlLlX3u2XBPBrY6I8Jct3mVR7W9AlOBrliLGl6EmtyiTO
            mprJZkFc0gYZm/FU2xzFmjenTRevwlwWtD8mkqDI4xdIN9pBeojfWRLqIJEcXsHS
            XgEJXQflLJ8o3xyRnwCF/tiBYYLP4hET6tG7axqQ6o2OAo7ME3DRfKz9OtTd8YLw
            RRxcm1zuq8sdTF7OEoY2Yc+187DRsq2xGPlqf7OKrh+Nr+0nuaDJeQwx0LG3dvQ=
            =uI31
            -----END PGP MESSAGE-----
          fp: 0F074212D05FD1A4875B719F174362ACE786CCDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
