---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.0.20-192.168.0.39
  LB_ADDRESS: 192.168.0.20
  MOSQUITTO_ADDRESS: 192.168.0.30
