# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: internal.timvw.co.uk
    SECRET_CLOUDFLARE_EMAIL: tim@timvw.co.uk
