---
- hosts:
  - masters
  - agents
  become: true
  gather_facts: true
  tasks:
  - name: cluster-init | set hostname
    become: true
    shell: hostnamectl set-hostname {{ hostname }}

  - name: cluster-init | enable cgroup
    become: true
    copy:
      src: files/cmdline.txt
      dest: /boot/firmware/cmdline.txt
    when: type == "sbc"

  - name: cluster-init | k3sup first master node
    become: true
    shell: |
      k3sup install \
      --host={{ groups['masters'][0] }} \
      --user=ubuntu \
      --cluster \
      --k3s-version=v1.20.5+k3s1 \
      --k3s-extra-args="--disable servicelb --disable traefik" \
      --local-path $HOME/.kube/config
    with_items:
    - "{{ groups['masters'][0] }}"
    delegate_to: 127.0.0.1
    ignore_errors: yes

  - name: cluster-init | k3sup join additional master nodes
    become: true
    shell: |
      k3sup join \
      --host={{ item }} \
      --user=ubuntu \
      --server-user ubuntu \
      --server-ip {{ groups['masters'][0] }} \
      --server \
      --k3s-version=v1.20.5+k3s1 \
      --k3s-extra-args="--disable servicelb --disable traefik" 
    with_items:
    - "{{ groups['masters'] | difference([groups['masters'][0]]) }}"
    delegate_to: 127.0.0.1
    ignore_errors: yes

  - name: cluster-init | k3sup join worker nodes
    become: true
    shell: |
      k3sup join \
          --host={{ item }} \
          --server-host={{ groups['masters'][0] }} \
          --k3s-version=v1.20.5+k3s1 \
          --user=ubuntu
    with_items:
    - "{{ groups['agents'] }}"
    delegate_to: 127.0.0.1
    ignore_errors: yes

  # - name: cluster-init | reboot node
  #   reboot:
  #   when: type == "sbc"
