---
- hosts:
  - masters
  - agents
  become: true
  gather_facts: true
  vars_prompt:
    name: "reboot_confirmation"
    prompt: "This will SHUTDOWN the cluster. Do you wish to continue? [Y/n]"
    default: "n"
    private: no
  any_errors_fatal: yes
  pre_tasks:
  - name: check confirmation
    fail:
      msg: "Abort."
    when: reboot_confirmation != "Y"
  
  - name: cluster-shutdown | k3sup worker nodes
    become: true
    command: /sbin/shutdown -h 60
    with_items:
    - "{{ groups['agents'] }}"

  - name: cluster-shutdown | k3sup master node
    become: true
    command: /sbin/shutdown -h 120
    with_items:
    - "{{ groups['masters'] }}"
