---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: kafka
      # version: 2.8.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    image:
      repository: bitnami/kafka
      tag: 2.8.1-debian-10-r43
      pullPolicy: IfNotPresent
      debug: false
    # ingress:
    #   enabled: true
    #   ingressClassName: "traefik"
    #   hosts:
    #   - host: "homer.${SECRET_DOMAIN}"
    #     paths:
    #     - path: /
    #       pathType: Prefix
    #   - host: "www.${SECRET_EXTERNAL_DOMAIN}"
    #     paths:
    #     - path: /
    #       pathType: Prefix
      # tls:
      # - hosts:
      #   - "${SECRET_EXTERNAL_DOMAIN}"
    # persistence:
    #   config:
    #     enabled: true
    #     existingClaim: homer-config
    #     mountPath: /www/assets
