---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN/./-}"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
  - "${SECRET_DOMAIN}"
  - "*.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_EXTERNAL_DOMAIN/./-}"
  namespace: networking
spec:
  secretName: "${SECRET_EXTERNAL_DOMAIN/./-}"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_EXTERNAL_DOMAIN}"
  dnsNames:
  - "${SECRET_EXTERNAL_DOMAIN}"
  - "*.${SECRET_EXTERNAL_DOMAIN}"
