---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${INTERNAL_DOMAIN/./-}"
  namespace: networking
spec:
  secretName: "${INTERNAL_DOMAIN/./-}"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${INTERNAL_DOMAIN}"
  dnsNames:
  - "${INTERNAL_DOMAIN}"
  - "*.${INTERNAL_DOMAIN}"
