apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# renovate: registryUrl=https://charts.jetstack.io chart=cert-manager
- helm-release.yaml
- letsencrypt-production.yaml
- letsencrypt-staging.yaml
- secret.enc.yaml
