# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:HTXqRQ==,iv:sBl097QAuLIRZCYaaXHdrUMoHneV8TcVe6hQqBHqzDI=,tag:OlgfAd3dISqibSVMnRPJ5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-12T21:31:28Z"
    mac: ENC[AES256_GCM,data:WN07fA1+CybkOep7RU0PYmmvuq3uu9QLexrMG+EOZN7BUi/rS/bGPN6mpQwDQhcaGHD9/sHwmVrHVMKSyisVDgI8Bi59xS6AlXA+gvY3U8PFLswjMnVlUavQrd2rx2eGt26mooIlI6iDkKly2S9ANSV+RNlCRBjUVTn/0PQ90Jo=,iv:2Et+0CiTlJfEfVCTQ2NUWR4rCB4xatMUOQ/4yyqAuHQ=,tag:1p/0iQzp4f9PfEGGcsX9Pw==,type:str]
    pgp:
        - created_at: "2021-06-12T21:31:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4KcvqgHb192AQ//Yq3tGKQbcgg46QuTec3erPhe9kNMfS0GZKxd0n+n+Rqj
            yvjuwIKwNzzpQ8myXzBeEl6wkNRcCsWiLmRipNUXso1bBQg5zz0EoDx3Ql0c2pwN
            Z2wXPr29/O18b8slnfU4Ch+X6Lh7jKhxrOXhttlcHVtzMK6GQM5Y7ZwKyZ2QJVI9
            EoMI7rGxHNiNv4gzJBzzXFVIUFWtvmov7afO6RCJXsP6+/mR0eAqO5QukljYu1Bk
            KLduKXmR95HvOBjdw3LuXJMSaYAt9/DOOvtZx9gtscz0XkVs6bwuHLTYYisu5OH7
            NV5K8Lo9Q+RXsc8Hh4JbBMZKD+q0+CYz92Q2K4PkEBSNbNNvfRMw9GkeMszAZ7/m
            nKjcqLHRHpDQz6n5hElwWiJxBJBgOsdJNWDGpJH93bl/nqRMMLrKN1vQn1tViOHZ
            1b/aLNPKxOzCBwVj42fSKP9QmKWbgSsTWdEBJBUjo/x4XMSXRxYMgtyfhc8q6xHW
            sL92HYuOldR8JBfuFB1T10k1leXTETCeCjJuFUeITeX9QWlx/UHGDReCMUDbB50a
            wWPQnLULSL8vKoSEOwQQlRhJuWDvHWqLXi1ZE034dIUmVabOgNrrlmBaoVfln8XT
            B1bcVtKqs0zpAnDiF9es9Gx8/ZvDarSLQTZ21hJYZw9hJ5AP0Yw2ASZw5b+qH4PS
            XAHRCg7iPtYhWGOVo80/0nOUQmA7FeQ0ofXjLlDLkemkapVpcfNjdia+fjm7gfcj
            AGPyj/BlF5mqDz0IGSV4DiRnPzCcMhe/1ABpxxt0H5Rip5kifeJk7u9soGFm
            =svwX
            -----END PGP MESSAGE-----
          fp: 3627F1BFED9A91B9D1098A902975378CB9A1B903
        - created_at: "2021-06-12T21:31:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxzJHnRk0chmAQ//SXuAAnfqGxgxJ0bi4dXJq9m8Ajl83znNgzh8Wg0324eC
            1yg5SdsOF60ZH5Wnahw53o5A/JcRYDykEYQIHLccVnEMbxQzJhqFHUHMTMG6j/gK
            9w8u6exLCrGLRIh0ECfcfBCLlTLJW2y6CpNn0hMAgK8hPEgF25pAMCFSuWxrsA4Z
            30Q42e3UrWvSBJ9WK/nje5boWWK9OxXkpEO/OD2M7tkMOr0TQhm7CWIRpZfI2/4Q
            ET4qi6wiIFdZqKkjtEFB/CfKV4yafhgJy0oE0XqClOGyouVGLvUHJBsHFJhBjHec
            NpcQg5zAu9HCeH0xbWguqM+qIld4s0CrP7JqHqxN9DckH5tHdnk0qc+BvzGYkryc
            nVu7fH+wzxqc6mqIHDZZO7wp7K7sM3ckvBc18Hl/ueYWudQm9OjjWwj7KB1PKU7V
            o5hYUW2i9HGC2sKeswqzH3DiLnWGrn1XJ4RH9b0bJ8JJw01RbWCRsIyUI/NG/G3L
            a3MOaFr5thRolwPBBO4ExNKqE7I3CL/8IT1WM9wNSr5Rxkr8NT0av5+YGKhDugA2
            dxtn6YRVxCM2PL+2511qzAPoZv/Df/jfSw7CiMzsxIdHVdrIhq1p44nns0y8QG21
            IlxVvFSRoHAkNK5o1Ivk32M2PcqNbSQuOoTanxxBhQ0NAXDnOxdp074ngpUTeHvS
            XAEvBycmJynvIjeGLzfhbI1J8A3JSon1cHQvyLuIU+cXSXmUuWfiLk1rVuRSsVC2
            +1KvU8mswxOmocUGm6+2FOnJ3DkmtxQPzRP2nZ8f+JxWDI3oQbzGMz9CE/Q3
            =7wJs
            -----END PGP MESSAGE-----
          fp: 0F074212D05FD1A4875B719F174362ACE786CCDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
