# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:i931Evc5R9qoEa7YGF2O+pCOIlbQbsaSSlbZuNJh6BQKZgUWWCfhuw==,iv:f2JB5X5aCO/fobtaH8QzJA+FGOU6TSpcXClXJodhGOQ=,tag:QeFNC3/4WBN8adJNR94Gog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-22T12:37:54Z"
    mac: ENC[AES256_GCM,data:BnSqxIROt2Op2NXtNThYVsCMdXHn+a63TrI7Vg9q6sloH11AmEvR7kkOXPV19KWviLBgheN6DCCejY78xr+IOC1qaFx3rFoCrmAHnT/8jTJNnSnO8VkmWt2M7m1+PWokSl5nSnRJWaqF19pBS4XAspnZ3/e8ikLuf7nTU3XqE74=,iv:G8gCl1SKR6/qGRQTKL1wKhvMIxPHbYWp07O8tkzNrbk=,tag:tN7ZhgW1j4fLPFx3FtOyvw==,type:str]
    pgp:
        - created_at: "2021-06-22T12:37:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4KcvqgHb192ARAAs0pyaWI2bjQ2oWGo2g4iCY0EAwdQyaQh1JYyRZTM+u5P
            3LPTm5p0jfqVtTF9fQQPV7FGjqqM6Ds6s1x5UyTxZx9xcqeWBDUBQrFlLxh6HpFU
            2fHiJe9d2Zh2xfkHIdpadQ4EKZsQDmEEmhfR0RxKpYunXf+3DIVmcgukep2SCNsV
            GoJWzwO5L7q42cl+Bo4CCDziNXNr8MuuvyrcmVPdT4BBvbxbheaJRxZsZai4vjUT
            aVpISjICvxjkwEEeIfIrHzOlfMdTfJPHztl2VvzDPPfIhLc8bAo5iPziQF5DdJbO
            l90XHAV+Yq6Zwq9wfWIqZaK82O8/SumbNb5A8iyQSjpNUJGKOebjoaLAmZOb0gXH
            mXu/eZ5NqjCx5//XQCXypoxiut6Ia+ZupzYnYD3j7zo5meQTzmA07R58yg1PAFv5
            U+EYAKNdxbxBLjN8+j0nfR+4fG9yvQatIDVR+998KuVxxZGKrtqJASaN6OdpiKci
            1eKFfPnnzhoM9glOelwRdFxbX0IKX0/Ab1Y6hTEohPjXgM1/8L4xq6f/CZM+uKgy
            /Fnj4XXbdqvoOuywuVXb31FG61nVOl6lEWehfF2MyCzyEFEiSKMdElp1ufkNAeTS
            FGBUefOwIZlM6P2OB4MEcC+QKH3Ydk/e9KdUbOSyDQODKq/ggDfvgeCOetse4r3S
            XgGaMNF9IflOi5spYh4xGG6G/toHVbZgitGo7ZSYif/LANF3ilJkZq/yXuHJ1vmN
            PTFTiA9UbDDd0CKt+mmqas4Kp1CoHcPIrKdjt2DvPzaUhRNVx7k70yFqotm6hyQ=
            =jzNC
            -----END PGP MESSAGE-----
          fp: 3627F1BFED9A91B9D1098A902975378CB9A1B903
        - created_at: "2021-06-22T12:37:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxzJHnRk0chmARAA28EiU78lqZMHtC77CQwhNaCkjmzgdVYKXIO/a2JCDFRb
            VyCvUHn6imdePqMGUpAzEdijM2KE+QnalKiIM4S5CwEIWvhFy8mTdArd0f3Jb8bg
            swgXzCq+KScaK2Ruw5ot/XPcm8OrC29gAJjH/Ekrf53/phhDkuHp6GvIDVO+VJcG
            hX3eqk1GIwHCZKE0yoLrB0TbnI0NPez4/kX3VCz5D/VzuekduoAo+DB4uadAki54
            +ZPvhtZp8pnXvb2Sy93Tv7u03czVVRZfgRfWvK/wnA+1DCqdyuz9dP2akKBb4Lub
            XMGTMA4ilGjmpprM9THP1WwPVbvs7288fKsdQsvytUkf8dUDKNntlhHvgbTZI6Yf
            LHy0WGXnAkfbXd4ey7Ps4TmEVtUUoiCY6j7bX6kgs9Z7rc50V4+IIaR+w6WwDgVH
            lS0v7IiKezWug3PIEh3puPVHdG+MZ8cJUlE3/U3mtp3EOHoAXDl6zDmU4C7Zkj7Q
            1ktCd73sHB7olptI5LlYAVyQogMLYMTkKz9jonp9FyW1+Xc1ABWLpCx1kI0pHqnS
            94pwERF87JPxfJFCpPFJEOergBPtWvKNW4RPUoiUJtEnauTjHXTERdc+JNRvkjIy
            NTGmyrtorML6gdYue0sDUpV/QBjxr8xpQvy6VlU7BlqTyBXsLfVdYzAvX4j+TlHS
            XgGbWOYU5e+CaUYUhcplaKJ6f1kwgVI1uTKwfNCFxUWG72BgJxF/a0XpxTaKTNfc
            1VHUoy3JGIMWoTWGgvwCu3jKVhQHRk6DM0MmNqxDZv00h+zy9jRta/DLVeEC1BY=
            =6AHU
            -----END PGP MESSAGE-----
          fp: 0F074212D05FD1A4875B719F174362ACE786CCDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
