# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:ZjC6QMT2KKJix768OxW0XpzWGnNqhwplPJKgv2a+FUZt8seSuuP5NQ==,iv:uKmyxpNMEpAC5syml3vHLNQXNfattCZDlQSjx6z6Y2c=,tag:Pbmr5FYNIn/skIqF0QBAXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-14T20:50:51Z"
    mac: ENC[AES256_GCM,data:PmuILTSNaWl8kDHrmglyEt+50uJK6+4Z/Uw+YOfi8HojPq5tcBORGyT8EdnjVr6fI+eUkup0jVEQsD0gYKOk3hI2Lh0TpVAi9j4DSGqRELhIlA+tzIiDPAskYXQnW9KsPkVEuMoEZPnkXdHEta6Q5CkMqHjYur1AqrOltLSxZng=,iv:THyGXDsZiBl0yneFhsOcvN6g/nfdjM7XNja1TdtrTQQ=,tag:ar/SEV1M1+k6UJ4nXmH59Q==,type:str]
    pgp:
        - created_at: "2021-06-14T20:50:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4KcvqgHb192AQ/7BjH71uIA/dH1Oqv7MdtXMTGfPHv/8Utr82qzXeBUXYXW
            4EDO/Z4OXB53HqCquU8Vqt1/xNXQimppo4AwCn47IP5hAIARg08uVuK7bCSXBvbR
            Hkso/p3921x1supE+YazlLrekMzT41fQ1VAuNdPDrc0fGiVRsl0VociBmhDee3ck
            qxrZi7ctxLjXy+cPIX5aymoJwLmuFZd3WdO3NU5AUnqx/s5YwxNOLeQtEIlW7H1g
            OObUzytLwMXv9q6EhT4ZPeFNbxBbO2CL9ZeUKxHR8GSIxQP773S6ZOqV5fXGHk6Z
            rnDI4paXw9WGIYjphVnmpkPOAIncXOobKsaS2dh6XbZsdvqDDAZOHF0JJNx/BCWS
            K89c9I3YnQEa/Gy/sOvj9tyFfLWj6aQYTU3hkejiYw6ABKeY0RDaSI9Pbo47z764
            BShlxNvcfnYsDKuKYY3yqHTHdVVPj8vCk0CiGXOi0fgLrRwnAmJPXfR7PXHCo269
            AcU6SnLk8WSMMYoX6foUo52vJ5zODkVUED0bIiYAU9IsvjJjlkpqWcmmG74IAnXy
            W/eP5U+3Nnkw7FKa2qHbUC7+qEeTodZPyxgQXxGnSWfGK5TlP17YfzaURE/cszQM
            vXXh97h+p6AHZPd43fSfYjVlnJRZEtF6j/6HEnRFrrqvwMOb2OEh72dzR6ChU3PS
            XgH581WXZ3x8iQCBEvufrf+4lKVaRzmCUy53ib3HfAZDlBSTDIHADomCaE4+VL8p
            FzqkFpnlD1W/eMTP9QeJS3nA/n2HZ7jtOY3So1f7Ay8o9aU04cj2RLI26KBzuZA=
            =T93e
            -----END PGP MESSAGE-----
          fp: 3627F1BFED9A91B9D1098A902975378CB9A1B903
        - created_at: "2021-06-14T20:50:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxzJHnRk0chmARAAtf4FmVE8DASWf1rrIIwAoVFXTjCnS7yZjG989yI9hd0J
            fg2t07kaVAnWM2zVDfFjoZe+UPwHO1bFCFCSFEHVT1uInz2tUlSoB8jmGUWSK7NF
            t5p7zwrMhbKp2GzoZ2abRDu0ow62b5ImyUSgWb/mQOIyjVGZCwktI1Wd/KXpcJTl
            d2C1R3yfFy7Nw9QoPyrcSrKmONhOzROgg9tm5BcK5JlIYXhlb1JnU54OrhB2os1o
            AVR3mGHhlJWZ1HwXcsBX0q6O5XNTpm9IQzu0Q4vvw1Kj58weTPe5gGboB1jiLYmb
            iKzlR1V/I0to8qn7SWTZ17wfw9PLlewKOtluibkU8Ib6rMLrkohw2rFj5UEQpMfy
            Oqwh0XwUwlH5HNl1Y/HSANkUcylraPt2DcG5DYv+AbzRl4YrGeHlCAwpsHaABt9j
            Gf5k2UBO80B7lSsBFUG6Gh35M+1V6qy2GxztsJUHXnzgZs+Fz7XRPVF1Z9laLwQ+
            u3lFcqnGz7slIpGyMYXyZEjcVd9hAFh9uzLCmtrEJ5GQ+ODeN4ocJdzG1pwkTykG
            2FYMHVktr3hDNDPypPK770mmeQcpHTvMfgj6jUURFmfT8Y+WqIN3M7tOFBJPba0h
            caqszcfG8QqwgM393ETTlGn0AIdDr4spItZs2XdzS+cHsUqfDdLv5HlN/a0WmoTS
            XgFnMvmkBdnSHTAx4jqJhisSTiMGcG4oZKJA3cxWZ3nJEZMgWO74ULKgVHBzzxzF
            CuYIz3WEThVdUbkkvtpigtK31+jTuSj8p9/wm1MEm0DHQXEXoRJnBTNzBiiHReQ=
            =kGnc
            -----END PGP MESSAGE-----
          fp: 0F074212D05FD1A4875B719F174362ACE786CCDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
