# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:WHuLsmkmvnwZ/7Ni9hdFjZSi4p1C1jLZyYQkAy9acmUO6Hrq+LD6Fw==,iv:sfsFikwvySipJ9L8S8ujQUKJtyAnYhBdEweik6r/cZk=,tag:Vo8VjvFfT1k6Q0f7jsfdEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-13T10:02:53Z"
    mac: ENC[AES256_GCM,data:bA/cwunIPqLZ0HL/w72uPC03ph8vlKCd4X21Vy7C4p+tvbbukR9zSS6URdiXXcCDBAWelGClTAKaheadilKEeH3W8weB7Qwn/15kDsuwZ+rVthOd7mEB7lUbeflNw+qaUhXnXUrDr6jpH//7RHJ4iul7gm5HKFlRqR+ISc24Xzo=,iv:+QR0TlI75oz9dxYWvjbRoT5U9vrIxV1zNaWXBDYsvtk=,tag:u43nWzxpnRCVhIc+7x1iVw==,type:str]
    pgp:
        - created_at: "2021-06-13T10:02:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4KcvqgHb192AQ/9GpifmO2DE2feThoJLlZLhNU19uP9LHC0qj4teOntklbH
            ah0H5TRQFN7GrhEDaoYP+BGwuD0GbGcDK8AULw3Wj+4QteNOXM/8rE4B5Iewfxq+
            wIdkmOP9TwnrYCkUBkeu0/5SxGwL44sC0UiQ2TObZd/81oRkbLHmb/OdSoMqyzXW
            pGM+gtvqElOj1/yNF5qj5jENEHDdCUCE68FYHK+FE8lzNskZnjyR4KqRCfAT8qtd
            8jEYUyiCCZR/H4QcSj/tSfy4k4Hqa9puDzREacZodh1+WWvCU4/0dQRUsFc9AIXg
            FUKXQY8iyCLw+9uhpPaWvAzhzAq6sDfVG7IfgCMP/uSyFvH6IPJG5IXEUo49thb3
            QruE2AujkCiEFtVAIJsreI2wjatPLlubHubsldbfRW6ixZf5QbVE75jwGzb0xznq
            kANHJ8703RR79fmboACvM8WRveonmkAdK4JzrVacmkh8/GsCSLxw2HwEW04kZ7ZK
            +0wRRNb5g9396gmFp1OkyJnEqMDX1oDQMfaccqHPwr69LCAbFd9RqA73Kbabg0tN
            32SYeNOknNs7aAY4Jtmv7E5spHktyEoL79MMQSO8APYFM34QtHGW4tr9XbvJ6DXx
            VC0CZq/GNp9BzYlB61u4XzoQLXsnvXX/BOkHB2QvGSgPp7RKvVbutVCIBodfXKnS
            XgHin472ObrwdY+wAfczqxtzUgVaPkqGF6lbn6hOGgI/VzgLHcSlp3QqrAPmZRSM
            Es+sJK2gV6O8WFUrJ+5KaniTN0aFkd3CHv90KldFfEOXXhxoD4zSI1saEpNFDGo=
            =SubJ
            -----END PGP MESSAGE-----
          fp: 3627F1BFED9A91B9D1098A902975378CB9A1B903
        - created_at: "2021-06-13T10:02:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxzJHnRk0chmARAAoZ0MLwjkww+A/jAWBsiY5EqSF6Tc3yvvSJIfNFm9ZBrt
            dzjPzW4cQ54fEzmHpHWVtNTdoHkUr7R9Z7CfrRlyxzeKvhIkXwM5w15Yp2METWev
            5UQBeuUzwxLLgxR1B08n8zUqkzfM3A+ykb+8h+yRLG1JBNPT8CbnovrM1+KB9C63
            cJchNMEvQTPHqdqd49NE5j4IDQG0Sz8pznreoqGiDJnaNWtkNp3DSYcMKdpd2GoI
            5kZqUqAvQrZknpgFbP2cTGvwkfmQx7tWGMWa+mRaYiEqfBVUz9zYuRmGxJz4hmWJ
            9Kme/wtV5tdxiXVi9wIzLVAs7jWd/zN/XBXX8XoWoDSb+ZyXZY0nPw24VBIH8a0F
            wizsvHP5XIqGZvsW81HIML1TrRoUlUEay6SqgepWCBbYZVNyM9zPWqGNVjA096BX
            NQAhNt3bsZcw6aM5tkXQ/K/KiJmLoPYshPoPrvFc3gyG+7AF9DzLKK348zvLHZlz
            SbsaWohJN7/GIYyrdzPLmfL/135ZdXqxEl50rh8ya+KH2rlLPkLx+ehoi84sKgZL
            B/LHa96w6+wvuNRt56fl8j7JR/ytyODTw6G0PaQJ+koMag2A+4Yb4Sb8QZUkEq7P
            28/rKpNUnmfMeYOxzkiPN0qQwuFPfwHE4ShyLX5sYn4gC/1gqXP0fBvVI+d/4E7S
            XgGTCnCUnsOLeuHK+fwxa6QT30QZZ+cFfYW49a2uOEPlj4VRpY9CZ7AhWEcwJMam
            K2ZqEZSXPJYVparMXvJyKQSM4TlZ8JCjkydfreeLybzGb2oFvH3qL1YS1u4SmAU=
            =PIJE
            -----END PGP MESSAGE-----
          fp: 0F074212D05FD1A4875B719F174362ACE786CCDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
