# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:/MXI/F3OgNVoVZLBbYB9+UtA/AMxq63iA1GMcUjcRYNecG7/J+P6TQ==,iv:VaTCaSLJNMQycoPlL1t2aaOYZs0ryBTp/NBnrCtRQt0=,tag:bBS5X9BBQAjbDTqzdzPP5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-18T08:10:10Z"
    mac: ENC[AES256_GCM,data:vUph8Wyeb+KXTjseW0IpeYdDSMBbNbUL4A0+jPWsEckusqlGlJD0B4BNYSc5Fosot+ETgbGNsw+uBLmFcuSrutKoCcAb0izbauFkZb5nZ8Hol0JIsiKMcrdgW49kAjUWs8UQdHoJ+Ai0AvY7nJ4LS6unlhtGtE7Yl72Z3gkJaL4=,iv:dlY1dvdN3CKd5D+XQitp7fTqj8+//2ee7rO0mNwPfvc=,tag:l8S0JfmWWxcglLyxtnkiqw==,type:str]
    pgp:
        - created_at: "2021-06-18T08:10:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4KcvqgHb192AQ/+Lj43zyY3kdkNym2y3Cnp//pQjrz8/UdDC+HLcKeHbikf
            +F8LV7gOoamI3JtTqNXTVKzBCtJtYehBC9m48IWsFLWQhepEWPyAhy+8mPErigx7
            UPOJLev3frE5OuA1cs8Brt9dH/mHF5TM59OYNRfq5wkxtg1AaqVqq2IeVQhwczba
            g9H5BbVzpVzMcH/Ajq/rV4R3SwXPKYGe+mboljRdzgJppwYgutnkXp+F/9TUkEg1
            kU7I0uslOKUzVy2GSlD+0ERfUP5g7SfzZXXIGy5MxOUs7C6ywUgsH5KuglLnsUr3
            qMu3r2PqmgyPByN7x4ystHsOxEgVZw+VcAlX+Yjg1ch+WMb13vWhhiBv85YH2AXm
            GtyE3RN2NZEcLpXt+PZmGHxICpLZ+3ibJBs7MIK4FxKa7O5Bq55RPOkPLjdK9kWV
            yDe8QwiVHZIKpLHaWV2XZ0EK53aYA6cfclnEIFM7sSebmcDssmlr/yp9NzSFS1Wm
            2LqNQs1spTrQ+Tl20B2zOBWdpXzWbXxELmL57fJ/pEBRcs4u+44P7J0I5fHA7bj0
            ErvjorlD8uOk44RiCC+29FNW3nfwtPOpZcPOFciltmE9qozEusHvwXNEpV+8J2y1
            oMLbzZ20g5TYRb502A0gNV+DchkSPTstbdfTMGFiGV7J7mn9e//+N++rTXXu61TS
            XAFtazOIYUsYMoRBQbTLAWKy3AGrO65guKA7VNnGyEyfPzaGZhIpVzT9wIx4TkqQ
            PGUKW0dZwFL5U6GkmtLRClEf+Fk1dQISEt28Ns2kGv386J8s+LBeTI704qhZ
            =cXBg
            -----END PGP MESSAGE-----
          fp: 3627F1BFED9A91B9D1098A902975378CB9A1B903
        - created_at: "2021-06-18T08:10:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxzJHnRk0chmARAAj4AgA0ZlywyMbTbJLDEpHEpqg8k0hopWtx84FZqGyAXC
            YwpgwPX1NgBF2Hj4mWnWpLYsqEBZjWMWMl9rW6OYzI/NkQlbMz/Foz4DjfAItpRC
            Nu9lpLg/bt79fflzab7M1H2O1fCyFwKv+ekOGLavtOegQmUkk7WFS57QUEKSyTwW
            d+062uh/+mx+OJzVGqYVhI/3mP2R1q5CRji9dqNxDuAheWCioqhd8WKpJN1cvusr
            qwQrrW2leNFFsX0y5aisgLUTI7nIPSbO36RbHMJR6os7mcCAsG6OS4W81DIFKFEJ
            imPGp/N/j0ucjcns139r42uD3nkqh0VuDqPsLlIseFYJ58OTyfGHLNqLpR9vuoKV
            /yM//QxbLQ3G+etoskM4yQDOTpji06PleRCUOHLKO9DVkz1pvzjJ5I81GH9jR2Dl
            OSiAU3R8CBZ2iAwFhzQz9JTDfF4r4xTzc/1plumSEIp+1eT7qfVe6s6tgSw8wQm/
            7GV8+OF2PhMbTy1hsvJWpfA1zbIoeqw4Q1B/iA7E1kku1diPA7qJItThTC44eSeY
            Ot9HeykIZTxA7isOAsm+a2XNF7Lw9s4DXWKcpPNlePJT7RMT/sFWH5D6n5GJQBFj
            97HFX7CpfhE5f1GlsbLspmyWa9zcRezF8o27F9H9pxGZRz2Ln03S5eYgqlkt9svS
            XAE5b8m+BcW3GunwTIatv+53VwF1UodBIHjR8sBmCJyS8ceXwsGwodkiYhesXQSw
            lRm/Qwz/8MwI06HRl+EtmNgMMr98d3p8dejygC+Nw7oVDXinQqCiYTOE2CuN
            =OFWT
            -----END PGP MESSAGE-----
          fp: 0F074212D05FD1A4875B719F174362ACE786CCDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
