---
- name: cluster-nuke | uninstall k3s master
  become: true
  command: sh /usr/local/bin/k3s-uninstall.sh
  when: hostvars[inventory_hostname].group_names[0] == "master"
  ignore_errors: yes
  async: 45
  poll: 0

- name: cluster-nuke | uninstall k3s master
  become: true
  command: sh /usr/local/bin/k3s-agent-uninstall.sh
  when: hostvars[inventory_hostname].group_names[0] == "workers"
  ignore_errors: yes
  async: 45
  poll: 0
