---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.11
      pullPolicy: IfNotPresent
    service:
      main:
        type: LoadBalancer
        annotations:
          traefik.ingress.kubernetes.io/service.serversscheme: mqtt
          metallb.universe.tf/allow-shared-ip: mosquitto
        loadBalancerIP: ${MOSQUITTO_ADDRESS}
        externalTrafficPolicy: Local
      prom:
        ports:
          http:
            port: 9641
        labels:
          app.kubernetes.io/name: mqtt2prometheus
    auth:
      # -- By enabling this, `allow_anonymous` gets set to `false` in the mosquitto config.
      enabled: false

    persistence:
      # -- Configure a persistent volume to place mosquitto data in.
      # When enabled, this enables `persistence` and `persistence_location` in the mosquitto config.
      # @default -- See values.yaml
      data:
        enabled: false
        mountPath: /mosquitto/data
      # -- Configure a persistent volume to place *.conf mosquitto-config-files in.
      # When enabled, this gets set as `include_dir` in the mosquitto config.
      # @default -- See values.yaml
      configinc:
        enabled: false
        mountPath: /mosquitto/configinc
        existingClaim: mosquitto-data
    volumes:
      - name: mqtt2prometheus-config-volume
        configMap:
          name: mqtt2prometheus-config
    additionalContainers:
      - name: mqtt2prometheus
        image: "ghcr.io/hikhvar/mqtt2prometheus:latest"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9641
            name: prom
        volumeMounts:
          - name: mqtt2prometheus-config-volume
            mountpath: /config.yaml
            subPath: config-yaml
