---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.11
      pullPolicy: IfNotPresent
    service:
      main:
        ports:
          http:
            enabled: false
          mqtt:
            port: 1883
            enabled: true

    auth:
      # -- By enabling this, `allow_anonymous` gets set to `false` in the mosquitto config.
      enabled: false

    persistence:
      # -- Configure a persistent volume to place mosquitto data in.
      # When enabled, this enables `persistence` and `persistence_location` in the mosquitto config.
      # @default -- See values.yaml
      data:
        enabled: false
        mountPath: /mosquitto/data
      # -- Configure a persistent volume to place *.conf mosquitto-config-files in.
      # When enabled, this gets set as `include_dir` in the mosquitto config.
      # @default -- See values.yaml
      configinc:
        enabled: false
        mountPath: /mosquitto/configinc
        existingClaim: mosquitto-data
