---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mosquitto
  namespace: default
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  endpoints:
  - path: /metrics
    targetPort: metrics
  jobLabel: mosquitto
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt2prometheus
